# Generated by Django 5.0.4 on 2024-05-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_AgregarPelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_peliculas/'),
        ),
    ]
