# Generated by Django 5.0.4 on 2024-05-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_AgregarSerie', '0004_alter_serie_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='imagen_url',
            new_name='img',
        ),
    ]
