# Generated by Django 5.0.4 on 2024-04-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePelicula', models.CharField(max_length=20)),
                ('duracion', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('fechaEstreno', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=12)),
            ],
        ),
    ]
